### ISSUE TITLE
prometeo-desugared.rg:2666: unexpected token in expression near 'disjoint'

### ISSUE THREAD

**Issue by purvigoel** [stanfordhpccenter/HTR-solver#1]
Hi! I've been following the Setup steps in the README and have installed legion and regent. I'm now attempting to compile the HTR-solver with the following, as per the README:

```
cd "$HTR_DIR"/src
USE_CUDA=0 USE_OPENMP=0 make
```

I am running into the following error:

```
/desugar.py prometeo.rg > prometeo-desugared.rg
EOS="ConstPropMix" /Users/purvigoel/Documents/legion/language/regent.py prometeo-desugared.rg -fflow 0 -finner 1 -fcuda 0 -fopenmp 0
prometeo-desugared.rg:2666: unexpected token in expression near 'disjoint'
make: *** [prometeo_ConstPropMix.o] Error 1
rm prometeo-desugared.rg
```

Just wondering if there might be any insight into this error message? Thank you!

**Comment by cmelone** [comment]
Hi, what system are you compiling the solver on?

**Comment by purvigoel** [comment]
I'm compiling on MacOS

**Comment by cmelone** [comment]
I’ve only ever compiled it on our Linux systems, not sure if macOS is supported.

**Comment by mariodirenzo** [comment]
Looks like you are compiling a Legion version without the parallelizer. Can you please check that you are using the branch `htr-release` from the repo `https://gitlab.com/mario.direnzo/legion.git`?

**Comment by mariodirenzo** [comment]
The new version of the solver that has just been uploaded in this repository does not rely on the auto-parallelizer.
I'm closing the issue as those instructions have been deleted from the source code.
