### ISSUE TITLE
process_schema.rg:364: attempt to call field 'endswith' (a nil value)

### ISSUE THREAD

**Issue by purvigoel** [stanfordhpccenter/HTR-solver#2]
Thanks for the help so far. I'm attempting to install the new version of the solver onto Sherlock. I can successfully build Legion as per the directions in the README, but when running: `USE_CUDA=0 USE_OPENMP=1 USE_GASNET=0 USE_HDF=1 MAX_DIM=3 make` in HTR_DIR/src, I get the following error:

```
process_schema.rg:364: attempt to call field 'endswith' (a nil value)
stack traceback:
	process_schema.rg:364: in main chunk
```

It looks like a lua error, pointing to `if #arg < 1 or not arg[1]:endswith(ext) then` in process_schema.rg . I was wondering if you might have some insight into this? Thanks!

Edit: closing this--it ended up being related to a hardcoded pythonpath in the shebang at the top of desugar.py

**Comment by ct-williams** [comment]
I seem to be encountering this issue, as well now. How did you end up fixing this error? Thanks!
